# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainw.ui'
#
# Created: Sun May 31 20:18:01 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainW(object):
    def setupUi(self, MainW):
        MainW.setObjectName("MainW")
        MainW.resize(433, 330)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainW.sizePolicy().hasHeightForWidth())
        MainW.setSizePolicy(sizePolicy)
        self.selectMasterButton = QtGui.QPushButton(MainW)
        self.selectMasterButton.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.selectMasterButton.setObjectName("selectMasterButton")
        self.masterPathLabel = QtGui.QLabel(MainW)
        self.masterPathLabel.setGeometry(QtCore.QRect(10, 15, 411, 21))
        self.masterPathLabel.setObjectName("masterPathLabel")
        self.rat1IDLabel = QtGui.QLabel(MainW)
        self.rat1IDLabel.setGeometry(QtCore.QRect(0, 80, 59, 31))
        self.rat1IDLabel.setObjectName("rat1IDLabel")
        self.rat2IDLabel = QtGui.QLabel(MainW)
        self.rat2IDLabel.setGeometry(QtCore.QRect(0, 120, 59, 31))
        self.rat2IDLabel.setObjectName("rat2IDLabel")
        self.rat1IDInput = QtGui.QLineEdit(MainW)
        self.rat1IDInput.setGeometry(QtCore.QRect(70, 80, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rat1IDInput.setFont(font)
        self.rat1IDInput.setPlaceholderText("")
        self.rat1IDInput.setObjectName("rat1IDInput")
        self.rat2IDInput = QtGui.QLineEdit(MainW)
        self.rat2IDInput.setGeometry(QtCore.QRect(70, 120, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rat2IDInput.setFont(font)
        self.rat2IDInput.setPlaceholderText("")
        self.rat2IDInput.setObjectName("rat2IDInput")
        self.startButton = QtGui.QPushButton(MainW)
        self.startButton.setGeometry(QtCore.QRect(110, 240, 84, 21))
        self.startButton.setObjectName("startButton")
        self.videoDurationBox = QtGui.QSpinBox(MainW)
        self.videoDurationBox.setGeometry(QtCore.QRect(150, 170, 121, 22))
        self.videoDurationBox.setMinimum(1)
        self.videoDurationBox.setMaximum(100000)
        self.videoDurationBox.setProperty("value", 60)
        self.videoDurationBox.setObjectName("videoDurationBox")
        self.numVideosBox = QtGui.QSpinBox(MainW)
        self.numVideosBox.setGeometry(QtCore.QRect(150, 200, 121, 22))
        self.numVideosBox.setMinimum(1)
        self.numVideosBox.setMaximum(10000)
        self.numVideosBox.setProperty("value", 24)
        self.numVideosBox.setObjectName("numVideosBox")
        self.videoDurationLabel = QtGui.QLabel(MainW)
        self.videoDurationLabel.setGeometry(QtCore.QRect(10, 169, 131, 21))
        self.videoDurationLabel.setObjectName("videoDurationLabel")
        self.numVideosLabel = QtGui.QLabel(MainW)
        self.numVideosLabel.setGeometry(QtCore.QRect(30, 200, 111, 21))
        self.numVideosLabel.setObjectName("numVideosLabel")
        self.videoDurationUnitLabel = QtGui.QLabel(MainW)
        self.videoDurationUnitLabel.setGeometry(QtCore.QRect(280, 170, 59, 21))
        self.videoDurationUnitLabel.setObjectName("videoDurationUnitLabel")
        self.stopButton = QtGui.QPushButton(MainW)
        self.stopButton.setGeometry(QtCore.QRect(220, 240, 84, 21))
        self.stopButton.setObjectName("stopButton")
        self.quitButton = QtGui.QPushButton(MainW)
        self.quitButton.setGeometry(QtCore.QRect(0, 304, 51, 21))
        self.quitButton.setObjectName("quitButton")

        self.retranslateUi(MainW)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL("clicked()"), MainW.quit)
        QtCore.QObject.connect(self.selectMasterButton, QtCore.SIGNAL("clicked()"), MainW.selectMasterFolder)
        QtCore.QObject.connect(self.startButton, QtCore.SIGNAL("clicked()"), MainW.startRun)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL("clicked()"), MainW.stopRun)
        QtCore.QMetaObject.connectSlotsByName(MainW)

    def retranslateUi(self, MainW):
        MainW.setWindowTitle(QtGui.QApplication.translate("MainW", "control", None, QtGui.QApplication.UnicodeUTF8))
        self.selectMasterButton.setText(QtGui.QApplication.translate("MainW", "select master", None, QtGui.QApplication.UnicodeUTF8))
        self.masterPathLabel.setText(QtGui.QApplication.translate("MainW", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.rat1IDLabel.setText(QtGui.QApplication.translate("MainW", "<html><head/><body><p align=\"right\">rat1 ID</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rat2IDLabel.setText(QtGui.QApplication.translate("MainW", "<html><head/><body><p align=\"right\">rat2 ID</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainW", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDurationLabel.setText(QtGui.QApplication.translate("MainW", "<html><head/><body><p align=\"right\">duration per Video</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.numVideosLabel.setText(QtGui.QApplication.translate("MainW", "<html><head/><body><p align=\"right\">number of videos</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDurationUnitLabel.setText(QtGui.QApplication.translate("MainW", "<html><head/><body><p>minutes</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainW", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("MainW", "quit", None, QtGui.QApplication.UnicodeUTF8))

